### ISSUE TITLE
The min password length is hard-coded in the PasswordStrengthValidator 

### ISSUE THREAD

**Issue by AMilkov** [nkostadinov/yii2-user#10]
This way the property `minPasswordLength` of the user component is overwritten when the validator is used.

**Comment by nkostadinov** [comment]
Hi, you may be right that this rule gets overwritten by the presets of the PasswordStrengthValidator. The idea is that PasswordStrengthValidator has configuration for the most of the password validations used and for the sake of simplicity we included a predefined presets so that you don't need to write the rules yourself.
If you set the passwordStrengthConfig property of the user component to empty array then the $minPasswordLength will be effective. May be the default value should be empty array or the docs should explain this more clearly.
